services:
  backend:
    build: .
    container_name: library_api
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=default
      - DEBUG=True
